### ISSUE TITLE
Hey – not an "issue," just a compliment ...

### ISSUE THREAD

**Issue by SundialServices** [bigsassy/drf-react-redux#4]
Of the various "illustrations of how to use these tools together" that are available here, I just wanted to say that this is a particularly nicely-done and complete one. *(Starred ...)*  It's very representative of such applications and of good practices, in a very small space.  (And maybe, it's the first darned **.md** file I've run into around these parts that actually *tells* you something!) **:-D**  

Thanks for sharing!

**Comment by ericpalakovichcarr** [comment]
Hey, thanks man!
